### ISSUE TITLE
If you hit "return" a bunch of times, it will allow you to post a blank comment; we shouldn't allow this

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1037]

**Comment by wyattjoh** [comment]
Maybe something related to newlines not being stripped when a comment is posted? Should be checked server side and client side.

**Comment by kamos1** [comment]
Hi, @kgardnr I'd like to take this on if there's not a solution in progress. Otherwise, I'll pick up another issue.

**Comment by kgardnr** [comment]
Hi @kamos1! It's all yours! 👍

**Comment by kamos1** [comment]
@kgardnr whenever I run yarn dev-start, I get the following error. Do you know why that is? I use the install from source instructions to get set up.

> /Users/keji/hacktoberfest/talk/graph/hooks.js:183
  field.resolve = async (obj, args, context, info) => {
                        ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/keji/hacktoberfest/talk/graph/schema.js:2:29)
    at Module._compile (module.js:570:32)

**Comment by kamos1** [comment]
@kgardnr I just created a PR for this. https://github.com/coralproject/talk/pull/1072

**Comment by alinhle** [comment]
Fixed in https://github.com/coralproject/talk/pull/1072
