### ISSUE TITLE
Undefined object property access in cli-jobs.

### ISSUE THREAD

**Issue by meddy** [coralproject/talk#1242]
### Expected behavior
The cleanup command in the cli-jobs bin script should clean up jobs that have been stuck.

### Actual behavior
```
TypeError: Cannot read property 'rangeByState' of undefined
    at Promise (~/talk/bin/cli-jobs:68:23)
    at new Promise (<anonymous>)
    at rangeJobsByState (~/talk/bin/cli-jobs:67:10)
    at Command.cleanupJobs (~/talk/bin/cli-jobs:86:7)
    at Command.listener (~/talk/node_modules/commander/index.js:300:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (~/talk/node_modules/commander/index.js:635:12)
    at Command.parse (~/talk/node_modules/commander/index.js:457:21)
    at Object.<anonymous> (~/talk/bin/cli-jobs:115:9)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
```

### Steps to reproduce behavior
```
$ ./bin/cli jobs cleanup --config .env
```

Glancing at the code, it looks like the problem is that this line:

https://github.com/coralproject/talk/blob/master/bin/cli-jobs#L59

Is incorrectly expecting the variable `kue` to be a reference to the Kue library export, since `Job.rangeByState` is a static method from that library. `kue` is actually a reference to the local `services/kue` module. I attempted to provide the correct reference, so that `rangeByState` was correctly called, but the static methods rely on the redis configuration being applied beforehand. I would assume the best way to handle that is to abstract that configuration setup in the `services/kue` module, and export it, but I figured I would run it by you guys first.

**Comment by meddy** [comment]
😞 

This was fixed.

https://github.com/coralproject/talk/blame/0af8a3115477a96ea58761f669276a71f2cb1d1e/services/kue.js#L173

My bad!
