### ISSUE TITLE
New custom build will fail with slack-notification plugin

### ISSUE THREAD

**Issue by acheraime** [coralproject/talk#1444]
#### Do you want to request a **feature** or report a **bug**?
No

#### Intended outcome:
Custom build with additional plugins

#### Actual outcome:
build will fail  with below error 
```
Error: plugin 'talk-plugin-slack-notifications' could not be required from '/usr/src/app/plugins/talk-plugin-slack-notifications/index.js': Duplicate parameter name not allowed in this context
    at Plugin.require (/usr/src/app/plugins.js:187:9)
    at plugins.forEach.plugin (/usr/src/app/plugins.js:236:14)
    at Array.forEach (<anonymous>)
    at PluginSection.require (/usr/src/app/plugins.js:234:18)
    at PluginSection.hook (/usr/src/app/plugins.js:254:10)
    at PluginManager.get (/usr/src/app/plugins.js:310:38)
    at Object.<anonymous> (/usr/src/app/graph/resolvers/index.js:73:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/app/graph/schema.js:10:19)
    at Module._compile (module.js:652:30)
/usr/src/app/plugins/talk-plugin-slack-notifications/server/hooks.js:13
      async post(_, _, context, info, result) {
                    ^

SyntaxError: Duplicate parameter name not allowed in this context
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/app/plugins/talk-plugin-slack-notifications/index.js:1:77)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c WEBPACK=TRUE NODE_ENV=test ./scripts/generateIntrospectionResult.js
Directory: /usr/src/app
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/usr/src/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "generate-introspection" exited with 1.
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c npm-run-all clean generate-introspection
Directory: /usr/src/app
Output:

```

#### How to reproduce the issue:
Build talk from scratch make sure to delete any cached image. Try with slack-notification plugin included.

#### Version and environment
Unbuntu xenial, CentOS 7
talk latest

**Comment by wyattjoh** [comment]
Great catch! Will address shortly.
