### ISSUE TITLE
Cannot read property 'hget' of undefined

### ISSUE THREAD

**Issue by icco** [coralproject/talk#1558]
#### Do you want to request a **feature** or report a **bug**?

Bug

#### Intended outcome:

Our organization name should have changed

#### How to reproduce the issue:

```
$ docker exec -it 15fbb50608ac cli settings change-org-name
  talk:config reCAPTCHA is disabled, required config is not present +0ms
  talk:util 1 jobs registered to be called during shutdown +0ms
TypeError: Cannot read property 'hget' of undefined
    at Object.cache.h.get (/usr/src/app/services/cache.js:282:36)
    at Object.cache.h.wrap (/usr/src/app/services/cache.js:313:29)
    at Function.retrieve (/usr/src/app/services/settings.js:37:38)
    at Command.changeOrgName (/usr/src/app/bin/cli-settings:17:42)
    at Command.listener (/usr/src/app/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/usr/src/app/node_modules/commander/index.js:653:12)
    at Command.parse (/usr/src/app/node_modules/commander/index.js:475:21)
    at Object.<anonymous> (/usr/src/app/bin/cli-settings:53:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

#### Version and environment

We're using 4.3.2. 

Our dockerfile is 

```
FROM coralproject/talk:4.3.2

# Setup the build arguments
ARG TALK_THREADING_LEVEL=4
ARG TALK_DEFAULT_STREAM_TAB=talk-plugin-featured-comments
ARG TALK_DEFAULT_LANG=en
ARG TALK_PLUGINS_JSON
ARG TALK_ASSET_COMMENTS_LOAD_DEPTH=300
ARG TALK_REPLY_COMMENTS_LOAD_DEPTH=300
ARG TALK_ADDTL_COMMENTS_ON_LOAD_MORE=300

WORKDIR /usr/src/app
ENV TALK_PORT=8080
EXPOSE 8080

# Bundle app source
COPY . /usr/src/app

RUN cli plugins reconcile && \
      yarn && \
      yarn build && \
      yarn cache clean
```

And we're running in ECS. 

Our redis is 3.2.10 on Elasticache

Mongodb is 3.4.14 on mongo atlas

**Comment by kgardnr** [comment]
Nat, can you test this PR and let us know if it solves your issue? Thank you!! https://github.com/coralproject/talk/pull/1559

@icco

**Comment by kgardnr** [comment]
@icco fixed for ya!!

**Comment by icco** [comment]
Sorry didn't have a chance to test! But yes, this looks great, thank you!

**Comment by kgardnr** [comment]
No worries! We actually found a small bug and fixed that anyway :) Thanks Nat!!
