### ISSUE TITLE
Module build failed: BrowserslistError: Unknown browser query `dead`

### ISSUE THREAD

**Issue by emilyyount** [coralproject/talk#1639]
#### Do you want to request a **feature** or report a **bug**?
Report a bug

#### Intended outcome:
Run `yarn build` during an initial install. 

#### Actual outcome:
Process fails after repeating this error multiple times. 

`Module build failed: BrowserslistError: Unknown browser query `dead`
    at error (/Users/emilyyount/Code/feature-talk-test-2018-05/talk/node_modules/browserslist/index.js:37:11)
    at /Users/emilyyount/Code/feature-talk-test-2018-05/talk/node_modules/browserslist/index.js:222:9
    at Array.forEach (<anonymous>)
    at browserslist (/Users/emilyyount/Code/feature-talk-test-2018-05/talk/node_modules/browserslist/index.js:196:13)
    at Browsers.parse (/Users/emilyyount/Code/feature-talk-test-2018-05/talk/node_modules/autoprefixer/lib/browsers.js:44:14)
    at new Browsers (/Users/emilyyount/Code/feature-talk-test-2018-05/talk/node_modules/autoprefixer/lib/browsers.js:39:28)
    at loadPrefixes (/Users/emilyyount/Code/feature-talk-test-2018-05/talk/node_modules/autoprefixer/lib/autoprefixer.js:56:18)
    at plugin (/Users/emilyyount/Code/feature-talk-test-2018-05/talk/node_modules/autoprefixer/lib/autoprefixer.js:62:18)
    at LazyResult.run (/Users/emilyyount/Code/feature-talk-test-2018-05/talk/node_modules/postcss/lib/lazy-result.js:274:20)
    at LazyResult.asyncTick (/Users/emilyyount/Code/feature-talk-test-2018-05/talk/node_modules/postcss/lib/lazy-result.js:189:32)
    at LazyResult.asyncTick (/Users/emilyyount/Code/feature-talk-test-2018-05/talk/node_modules/postcss/lib/lazy-result.js:201:22)
    at LazyResult.asyncTick (/Users/emilyyount/Code/feature-talk-test-2018-05/talk/node_modules/postcss/lib/lazy-result.js:201:22)
    at LazyResult.asyncTick (/Users/emilyyount/Code/feature-talk-test-2018-05/talk/node_modules/postcss/lib/lazy-result.js:201:22)
    at LazyResult.asyncTick (/Users/emilyyount/Code/feature-talk-test-2018-05/talk/node_modules/postcss/lib/lazy-result.js:201:22)
    at LazyResult.asyncTick (/Users/emilyyount/Code/feature-talk-test-2018-05/talk/node_modules/postcss/lib/lazy-result.js:201:22)
    at LazyResult.asyncTick (/Users/emilyyount/Code/feature-talk-test-2018-05/talk/node_modules/postcss/lib/lazy-result.js:201:22)`

Stacktrace: https://gist.github.com/kgardnr/bd1e2a923cb467cf55742071389e98bf

I followed the instructions for installing from source: https://docs.coralproject.net/talk/installation-from-source/. Everything worked until I tried to run `yarn build`. 

After a few Google searches for the error message, I tried backtracking and ran `yarn cache clean`, but that didn't do the trick. I also tried the solution in [this github issue](https://github.com/coralproject/talk/issues/995), but that also didn't work. 

#### Version and environment
Node version: v8.9.4
Yarn version: 1.6.0
Mac OS: 10.13.4

**Comment by kgardnr** [comment]
Hey Emily! Welcome to Talk!

Which version of Talk are you using? 

Can you try deleting the node_modules folder and running `yarn build` again?

If you keep running into issues, someone from our team can jump on a call with you.

**Comment by kgardnr** [comment]
PS I put your stacktrace here so we can keep the ticket conversation readable: https://gist.github.com/kgardnr/bd1e2a923cb467cf55742071389e98bf

**Comment by emilyyount** [comment]
@kgardnr Thanks! 

I ran these commands from your [install from source page](https://docs.coralproject.net/talk/installation-from-source/). I'm not sure what version of Talk that pulls. 

`curl -sLo talk.tar.gz https://github.com/coralproject/talk/archive/master.tar.gz
mkdir -p talk`
`tar xzf talk.tar.gz -C talk --strip-components 1`
`cd talk`

I deleted the node_modules folder and ran `yarn build` again. I got the same error as is pasted above. 

Happy to jump on a call!

**Comment by kgardnr** [comment]
Can you try skipping that step and continuing with setting up Mongo, Redis and your .env file.

And then you can run

```yarn && yarn watch```

**Comment by emilyyount** [comment]
@kgardnr: I skipped that step and ran `docker run -p 127.0.0.1:6379:6379 -d redis`. That seemed to work, but then I don't see a .env file to edit. I have my hidden files visible (we use docker for other things), but I don't see the file in this instance.

**Comment by kgardnr** [comment]
Are you setting this up to test it out or as the first step to launch it on Texas Tribune?

**Comment by emilyyount** [comment]
To test it out on a stand alone page.

**Comment by kgardnr** [comment]
Great! The simplest thing to do is go to the readme here: https://github.com/coralproject/talk

And click on the Heroku one-click install - you'll have it up and running in just a few minutes! You will need a heroku account which is free.

**Comment by emilyyount** [comment]
Okay. I will give that a try.

**Comment by Prabhagar06** [comment]
Hi @emilyyount , Did you found any solution to solve this issue? because i am also getting same issue :)

**Comment by emilyyount** [comment]
@Prabhagar06 I didn't, but the one-click-install ended up being a good solution for me because I was only trying to take Talk for a test spin. 

https://github.com/coralproject/talk#try-talk

**Comment by wyattjoh** [comment]
Hey @emilyyount + @Prabhagar06!

Could you try updating your versions of Node + Yarn? I just did a clean install with:

Node v8.11.2
Yarn v1.7.0
Mac OS: 10.13.4

And I did not experience the issue described.
