### ISSUE TITLE
Deploy to heroku button broken

### ISSUE THREAD

**Issue by icco** [coralproject/talk#1685]
#### Do you want to request a **feature** or report a **bug**?

Bug

#### Intended outcome:

Click the run on heroku button in your readme, and get a working build on heroku.

#### Actual outcome:

The following errors occurred:

```
-----> Building dependencies
       Installing node modules (yarn.lock)
       yarn install v1.7.0
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       (node:368) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
       info fsevents@1.2.4: The platform "linux" is incompatible with this module.
       info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
       [3/4] Linking dependencies...
       warning " > hjson-loader@1.0.0" has incorrect peer dependency "hjson@^1.7.4".
       warning "react-apollo > enzyme-adapter-react-16@1.1.1" has incorrect peer dependency "react@^16.0.0-0".
       warning "react-apollo > enzyme-adapter-react-16@1.1.1" has incorrect peer dependency "react-dom@^16.0.0-0".
       warning "react-apollo > enzyme-adapter-react-16 > react-reconciler@0.7.0" has incorrect peer dependency "react@^16.0.0".
       warning "react-apollo > enzyme-adapter-react-16 > react-test-renderer@16.4.0" has incorrect peer dependency "react@^16.0.0".
       warning " > react-paginate@5.2.3" has incorrect peer dependency "react@^16.0.0".
       [4/4] Building fresh packages...
       Done in 56.30s.
       Running heroku-postbuild (yarn)
       yarn run v1.7.0
       $ npm-run-all plugins:reconcile build
       $ ./bin/cli plugins reconcile
/tmp/build_e8dcc969fb4872814043fd1c740893fd/node_modules/env-rewrite/src/rewriter.js:24
            throw new Error('Env ' + oldEnvName + ' was not defined');
            ^
Error: Env MAILGUN_SMTP_PASSWORD was not defined
    at Object.keys.forEach.newEnvName (/tmp/build_e8dcc969fb4872814043fd1c740893fd/node_modules/env-rewrite/src/rewriter.js:24:19)
    at Array.forEach (<anonymous>)
    at Object.module.exports [as rewrite] (/tmp/build_e8dcc969fb4872814043fd1c740893fd/node_modules/env-rewrite/src/rewriter.js:19:26)
    at Object.<anonymous> (/tmp/build_e8dcc969fb4872814043fd1c740893fd/services/env.js:4:24)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
error Command failed with exit code 1.
       info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "plugins:reconcile" exited with 1.
error Command failed with exit code 1.
       info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Dangerous semver range (>) in engines.node
       https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

#### How to reproduce the issue:

Click the button in the readme, then fill in the app name, change the root url to match and change `NPM_CONFIG_PRODUCTION` to true.

#### Version and environment

Master branch

**Comment by kgardnr** [comment]
Hey @icco! Thanks for logging this.

Are you setting the Mailgun SMTP info? Or trying to?

**Comment by icco** [comment]
![pageshot of create new app heroku 2018-06-01-1148 03](https://user-images.githubusercontent.com/20201/41242369-524f821c-6d6d-11e8-8628-4f6dfe419848.png)

This is what I see in the create page, so I don't think that's an option.

**Comment by kgardnr** [comment]
Ok thanks! We are looking into this. Thanks for catching it!

**Comment by kgardnr** [comment]
Hey @icco thanks for reporting this - we've decided to deprecate support for Heroku one-click, so I'll close this ticket. Thank you!!

**Comment by davisshaver** [comment]
Hey 👋, saw that this was dropped in 4.5.0 and was wondering if the team could share a little context on the decision to remove the Heroku button? It’s a nice feature for devs new to project, maybe I can help out with a PR to get it working again?

**Comment by kgardnr** [comment]
Hey @davisshaver! Yeah, we just haven't been able to support it properly. But if you would like to submit a PR to fix it, we could add it back in our docs for others to use perhaps. Thank you!
