### ISSUE TITLE
cli-plugins create seems to be broken

### ISSUE THREAD

**Issue by smic1909** [coralproject/talk#1690]
Running `cli-plugins create` seems to be broken on master.

```
./bin/cli-plugins create
module.js:549
    throw err;
    ^

Error: Cannot find module 'env-rewrite'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/<name>/workspace/coralproject/talk/services/env.js:4:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by smic1909** [comment]
Running `yarn install` fixed the problem.
