### ISSUE TITLE
Error: Cannot return null for non-nullable field UsernameStatus.status.

### ISSUE THREAD

**Issue by smic1909** [coralproject/talk#1703]
As a followup to https://github.com/coralproject/talk/issues/1700, I am getting the following error now:

```
 talk:services:cache wrapMany: hit ratio: 1/1 +2m
Error: Cannot return null for non-nullable field UsernameStatus.status.
    at completeValue (/Users/<username>/workspace/coralproject/talk/node_modules/graphql/execution/execute.js:599:13)
    at completeValueWithLocatedError (/Users/<username>/workspace/coralproject/talk/node_modules/graphql/execution/execute.js:546:21)
    at completeValueCatchingError (/Users/<username>/workspace/coralproject/talk/node_modules/graphql/execution/execute.js:515:12)
    at resolveField (/Users/<username>/workspace/coralproject/talk/node_modules/graphql/execution/execute.js:467:10)
    at /Users/<username>/workspace/coralproject/talk/node_modules/graphql/execution/execute.js:314:18
    at Array.reduce (<anonymous>)
    at executeFields (/Users/<username>/workspace/coralproject/talk/node_modules/graphql/execution/execute.js:311:42)
    at collectAndExecuteSubfields (/Users/<username>/workspace/coralproject/talk/node_modules/graphql/execution/execute.js:749:10)
    at completeObjectValue (/Users/<username>/workspace/coralproject/talk/node_modules/graphql/execution/execute.js:731:10)
    at completeValue (/Users/<username>/workspace/coralproject/talk/node_modules/graphql/execution/execute.js:628:12)
    at completeValue (/Users/<username>/workspace/coralproject/talk/node_modules/graphql/execution/execute.js:597:21)
    at completeValueWithLocatedError (/Users/<username>/workspace/coralproject/talk/node_modules/graphql/execution/execute.js:546:21)
    at completeValueCatchingError (/Users/<username>/workspace/coralproject/talk/node_modules/graphql/execution/execute.js:515:12)
    at resolveField (/Users/<username>/workspace/coralproject/talk/node_modules/graphql/execution/execute.js:467:10)
    at /Users/<username>/workspace/coralproject/talk/node_modules/graphql/execution/execute.js:314:18
    at Array.reduce (<anonymous>)
    at executeFields (/Users/<username>/workspace/coralproject/talk/node_modules/graphql/execution/execute.js:311:42)
    at collectAndExecuteSubfields (/Users/<username>/workspace/coralproject/talk/node_modules/graphql/execution/execute.js:749:10)
    at completeObjectValue (/Users/<username>/workspace/coralproject/talk/node_modules/graphql/execution/execute.js:731:10)
    at completeValue (/Users/<username>/workspace/coralproject/talk/node_modules/graphql/execution/execute.js:628:12)
    at completeValueWithLocatedError (/Users/<username>/workspace/coralproject/talk/node_modules/graphql/execution/execute.js:546:21)
    at completeValueCatchingError (/Users/<username>/workspace/coralproject/talk/node_modules/graphql/execution/execute.js:521:21)
    at resolveField (/Users/<username>/workspace/coralproject/talk/node_modules/graphql/execution/execute.js:467:10)
    at /Users/<username>/workspace/coralproject/talk/node_modules/graphql/execution/execute.js:314:18
    at Array.reduce (<anonymous>)
    at executeFields (/Users/<username>/workspace/coralproject/talk/node_modules/graphql/execution/execute.js:311:42)
    at collectAndExecuteSubfields (/Users/<username>/workspace/coralproject/talk/node_modules/graphql/execution/execute.js:749:10)
    at completeObjectValue (/Users/<username>/workspace/coralproject/talk/node_modules/graphql/execution/execute.js:731:10)
```

My `notfound.js` looks like this:
```
const UserModel = require('../../../models/user');
var rp = require('request-promise');

module.exports = {
  tokenUserNotFound: async ({ jwt, token }) => {
    console.log(jwt);
    console.log(token);

    var options = {
      json: true,
      url: 'https://<url>',
      headers: {
        Accept: 'application/json',
        Authorization: 'Bearer ' + jwt.ssotoken,
      },
    };

    let profile = null;

    try {
      console.log('Start Request');
      //await request(options, callback);

      await rp(options)
        .then(function(repos) {
          profile = repos;
        })
        .catch(function(err) {
          console.log('Error occurred.');
          console.log(err);
          // API call failed...
        });

      let user = await UserModel.findOneAndUpdate(
        {
          id: profile.sub,
        },
        {
          id: profile.sub,
          username: profile.nickname,
          lowercaseUsername: profile.nickname.toLowerCase(),
          roles: [],
          profiles: [],
        },
        {
          setDefaultsOnInsert: true,
          new: true,
          upsert: true,
        }
      );

      console.log('Return User with id ' + user.id);
      return user;
    } catch (error) {
      console.log(error);
    }
  },
};
```

The log output `Return User with id ef0e3314-0296-489b-addd-23b161920700` is printed, so I would assume a user has been created.
Running the following code in `GraphiQL`
```
{
  user(id:"ef0e3314-0296-489b-addd-23b161920700") {
    id
  }
}
```

returns 
```
{
  "data": {
    "user": null
  }
}
```
which looks like the user has not been created. Any advice?

**Comment by wyattjoh** [comment]
There are a few issues here.

If you are creating a user, you can take a look at:

https://github.com/coralproject/talk/blob/c1d547e1b122aa5604f838239646733d9c9dc6fa/services/users.js#L487-L521

For how to create the user with the correct properties.

Also, the `user` graph endpoint is protected by default, and requires an administrative token to use.

**Comment by smic1909** [comment]
I will give it a try but the code I used was suggested in [tokenUserNotFound](https://docs.coralproject.net/talk/api/server/#tokenusernotfound) docs.

**Comment by smic1909** [comment]
In order to call the `findOrCreateExternalUser` function, the `ctx` needs to be present. Do you see any side effect if I just pass the `ctx` to the function (next to `jwt` and `token`) or is it possible to load/inject the `ctx` as an `require` option.

**Comment by smic1909** [comment]
I skipped submitted the `ctx` for the moment while I did a `null` check in the `findOrCreateExternalUser` method. A user has been created but at the time I would like to create a comment, I am getting the message `You are not authorized to perform this action.` displayed as a small popup on the bottom of the page. Is the message connected to the skipped `ctx.pubsub.publish('userCreated', user);` command in the `findOrCreateExternalUser` method?
From log output, the following user has been created:
```
{ status:
   { username: { status: 'UNSET', history: [Array] },
     banned: { status: false, history: [] },
     suspension: { until: null, history: [] } },
  role: 'COMMENTER',
  ignoresUsers: [],
  _id: 5b2d0c59c71dd73f9dbb8243,
  username: 'smic',
  lowercaseUsername: 'smic',
  profiles:
   [ { id: 'bf69302e-2551-4631-bfd1-e3723cdb60fe', provider: 'SSO' } ],
  id: '17e9f3db-b5b2-4d9b-a013-98e69e9a7b78',
  tokens: [],
  tags: [],
  created_at: 2018-06-22T14:48:57.362Z,
  updated_at: 2018-06-22T14:48:57.362Z,
  __v: 0 }
```

**Comment by wyattjoh** [comment]
You aren't able to create a comment because the username is `UNSET`. The integration is a bit tricky (we're working on it ;)), but you might be better off instead just replicating the contents of the `findOrCreateExternalUser` whilst setting the `status.username.status = SET`.

**Comment by smic1909** [comment]
Setting [this line](https://github.com/coralproject/talk/blob/master/services/users.js#L512) from `UNSET` to `SET` fixed the problem. However, do you expect some side effect changing this line? We will not support Facebook/Amazon Login (which code is using this method as well) but only our internal SSO.
Is there a timeline when you will fix this issue?
P.S: How can I delete a created user? In the admin panel it is not possible. The CLI doesn´t support it as well (as far as I know). For testing it would be quite comfortable in order to not create a new user in the SSO server for each test.

**Comment by smic1909** [comment]
Any suggestions @wyattjoh ?

**Comment by wyattjoh** [comment]
We currently use that method for creating users via our social based auth methods. I'd recommend just copying that function into your plugin as is in order to implement your specific authentication situation. Lots of organizations have different requirements in terms of how the user is created, so it really depends on your implementation.

We don't have plans currently to address this issue as we're currently focused on an update for Talk 5.0.
