### ISSUE TITLE
User name is shown instead of displayName though I directly specify displayName while creating the user

### ISSUE THREAD

**Issue by hminaeeBrunswicknews** [coralproject/talk#1863]
Hello,

I am using talk SSO with TokenNotFound plugin.
When I inject profileName directly into the metadata field still the user name is displayed rather than the display name I specified.

Here is my code:

```
const UserModel = require('../../../models/user');
module.exports = {
	tokenUserNotFound: async ({jwt, token}) => {
	  let data={"displayName":"HMtest","email":"minaee992.hamed@yahoo.com4431"};

      const user = await UserModel.findOneAndUpdate(
        {
          id: jwt.sub,
        },
        {
          id: jwt.sub,
          username: data.email,
          lowercaseUsername: data.email.toLowerCase(),
          profiles: [
            {
              provider: 'brunswicknews',
              id: jwt.sub,
            },
          ],
          status: {
            username: {
              status: 'SET',
              history: [
                {
                  status: 'SET',
                },
              ],
            },
          },
          metadata: {
            displayName: data.displayName
          },
        },
        {
          setDefaultsOnInsert: true,
          new: true,
          upsert: true,
        }
      );
	  return user;
	}
};
```

After running it on the client:

![image](https://user-images.githubusercontent.com/24658315/45382632-3cf7b000-b5df-11e8-91e8-f9aad5638802.png)

I see minaee992.hamed@yahoo.com4431 instead of HMtest. 

Based on what I see in the user schema in the code, the only possible way to have the displayName inserted in Mongo  is to use metadata:

[https://github.com/coralproject/talk/blob/master/models/schema/user.js#L19](https://github.com/coralproject/talk/blob/master/models/schema/user.js#L19)

as I am doing in the above code :

```
 metadata: {
            displayName: data.displayName
          }
```

Is there anything I am missing in my code which leads to this issue?

**Comment by hjanuschka** [comment]
try setting `username`  and `lowercaseUsername` to the username, and move the `email`  to the profile it self.

like this:

```javascript
const UserModel = require('../../../models/user');
module.exports = {
	tokenUserNotFound: async ({jwt, token}) => {
	  let data={"displayName":"HMtest","email":"minaee992.hamed@yahoo.com4431"};

      const user = await UserModel.findOneAndUpdate(
        {
          id: jwt.sub,
        },
        {
          id: jwt.sub,
          username: data.displayName,
          email: data.email,
          lowercaseUsername: data.displayName.toLowerCase(),
          profiles: [
            {
              provider: 'brunswicknews',
              id: jwt.sub,
            },
            {
               provider: "local",
               id: data.email,
               username: data.displayName
            }
          ],
          status: {
            username: {
              status: 'SET',
              history: [
                {
                  status: 'SET',
                },
              ],
            },
          }
        },
        {
          setDefaultsOnInsert: true,
          new: true,
          upsert: true,
        }
      );
	  return user;
	}
};
```

i also added a `localProfile` if you plan to use the notification plugin for example, it requires to have the local profile with a email.


let me know if that helps

**Comment by hminaeeBrunswicknews** [comment]
Thanks a lot @hjanuschka 

I tried and it works only when the displayNames are unique but when two users have the same displayName I will get the following error:

```
 http error
  err: MongoError: E11000 duplicate key error collection: talk.users index: lowercaseUsername_1 dup key: { : "hamed minaeetest" }
      at ./node_modules/mongodb-core/lib/connection/pool.js:580:63
      at authenticateStragglers (./node_modules/mongodb-core/lib/connection/pool.js:503:16)
      at Connection.messageHandler (./node_modules/mongodb-core/lib/connection/pool.js:539:5)
      at emitMessageHandler (./node_modules/mongodb-core/lib/connection/connection.js:309:10)
      at Socket.<anonymous> (./node_modules/mongodb-core/lib/connection/connection.js:452:17)
      at Socket.emit (events.js:182:13)
      at addChunk (_stream_readable.js:283:12)
      at readableAddChunk (_stream_readable.js:264:11)
      at Socket.Readable.push (_stream_readable.js:219:10)
      at TCP.onread (net.js:639:20)
  version: "4.6.1"
```
Is there anyway to allow duplicate username?

**Comment by wyattjoh** [comment]
You can use the:

https://github.com/coralproject/talk/blob/c19d4a433a0e1ab3453994affdfa5ed03becd6f8/services/users.js#L481-L486

function to create the initial username, which will ensure there won't be a duplicate.

You can also [disable auto indexing](https://docs.coralproject.net/talk/advanced-configuration/#disable-create-mongo-indexes) and remove the index manually, though it's not recommended.

**Comment by hminaeeBrunswicknews** [comment]
@wyattjoh  Thanks for clarification. 
I appreciate it
