### ISSUE TITLE
container build error with 4.7-onbuild

### ISSUE THREAD

**Issue by brocawernicke** [coralproject/talk#2198]
#### Do you want to request a **feature** or report a **bug**?
bug or question

#### Intended outcome:

tried to build docker container image with 4.7-onbuild tag.

#### Actual outcome:

Step 1/1 : RUN cli plugins reconcile &&             yarn &&             yarn build &&             yarn cache clean
 ---> Running in 21969ba69a86

['1/2'] 🔍 Reconciling plugins...

 +local     (l)  packages in your project
 +external  (e)  packages are external
 +outofdate (oe) packages are external but are out of date
 +missing   (m)  packages are not found

TypeError: Cannot destructure property `fetchable` of 'undefined' or 'null'.
    at reconcileRemotePlugins (/usr/src/app/bin/cli-plugins:140:37)
    at Command.reconcilePluginDeps (/usr/src/app/bin/cli-plugins:211:27)
    at Command.listener (/usr/src/app/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/usr/src/app/node_modules/commander/index.js:651:12)
    at Command.parse (/usr/src/app/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/usr/src/app/bin/cli-plugins:401:9)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)

#### How to reproduce the issue:

built container with following single line of modification in the first line of Dockerfile.onbuild
FROM coralproject/talk:4.7-onbuild

#### Version and environment

4.7-onbuild

**Comment by brocawernicke** [comment]
I just tried to follow build instruction on https://docs.coralproject.net/talk/installation-from-docker/, but I got the same error.

**Dockerfile**:
  _FROM coralproject/talk:4.5-onbuild_

**shell**:
  _docker build -t my-talk-image --build-arg TALK_DEFAULT_LANG=es ._

**Comment by brocawernicke** [comment]
I just make it work by building from source code. thanks.
