### ISSUE TITLE
Amazon DocumentDB (with MongoDB compatibility) is it supported.

### ISSUE THREAD

**Issue by brvaland** [coralproject/talk#2305]
I am trying to use Amazon DocumentDB (Mongodb 3.6) - https://aws.amazon.com/documentdb/ but when i run talk i am getting below error message.

```
MongoError: namespace name generated from index name is too long
     at /usr/src/app/node_modules/mongodb-core/lib/connection/pool.js:580:63
     at authenticateStragglers (/usr/src/app/node_modules/mongodb-core/lib/connection/pool.js:503:16)
     at Connection.messageHandler (/usr/src/app/node_modules/mongodb-core/lib/connection/pool.js:539:5)
     at emitMessageHandler (/usr/src/app/node_modules/mongodb-core/lib/connection/connection.js:309:10)
     at Socket.<anonymous> (/usr/src/app/node_modules/mongodb-core/lib/connection/connection.js:452:17)
     at emitOne (events.js:116:13)
     at Socket.emit (events.js:211:7)
     at addChunk (_stream_readable.js:263:12)
     at readableAddChunk (_stream_readable.js:250:11)
     at Socket.Readable.push (_stream_readable.js:208:10)
     at TCP.onread (net.js:601:20)
```
Any help will be appreciated ?

**Comment by kgardnr** [comment]
Hi @brvaland we do not currently support DocumentDB. If you'd like to contribute this support, we'd love to include it!

**Comment by brvaland** [comment]
@kgardnr - Thanks

**Comment by felixdro** [comment]
Thanks for information,

We are also trying to run Coral with AWS DocumentDB, but without success. I get the error message MongoError "system collection creation not supported". 

I don't really know anything about MongoDB but a guess is that this has something to do with the [differences between MongoDB and Document DB](https://docs.aws.amazon.com/documentdb/latest/developerguide/functional-differences.html#functional-differences.admin-databases).

But it could also be something else I guess. Anyway, I hope it will be supported one day in the future.

This is the the logs when starting Coral:
```
> @coralproject/talk@5.0.0 start /usr/src/app
> NODE_ENV=production node dist/index.js
{
    "name": "coral",
    "clusterNode": "master",
    "pid": 24,
    "level": 30,
    "msg": "mongodb autoindexing is enabled, starting indexing",
    "time": "2019-09-23T20:29:44.444Z",
    "src": {
        "file": "/usr/src/app/src/core/server/index.ts",
        "line": 187,
        "func": "info"
    },
    "v": 0
}
{
    "name": "coral",
    "clusterNode": "master",
    "pid": 24,
    "collectionName": "users",
    "level": 50,
    "err": {
        "message": "system collection creation not supported",
        "name": "MongoError",
        "stack": "Function.create (node_modules/mongodb-core/lib/error.js:43:12)\ndb.s.topology.insert (node_modules/mongodb/lib/operations/db_ops.js:329:54)\nnode_modules/mongodb-core/lib/connection/pool.js:397:18\nprocess._tickCallback (internal/process/next_tick.js:61:11)\n"
    },
    "indexSpec": {
        "tenantID": 1,
        "email": 1
    },
    "indexOptions": {
        "unique": true,
        "partialFilterExpression": {
            "email": {
                "$exists": true
            }
        }
    },
    "msg": "could not create index",
    "time": "2019-09-23T20:29:44.529Z",
    "src": {
        "file": "/usr/src/app/src/core/server/models/helpers/indexing.ts",
        "line": 39,
        "func": "error"
    },
    "v": 0
}
{
    "name": "coral",
    "clusterNode": "master",
    "pid": 24,
    "level": 50,
    "err": {
        "message": "system collection creation not supported",
        "name": "MongoError",
        "stack": "Function.create (node_modules/mongodb-core/lib/error.js:43:12)\ndb.s.topology.insert (node_modules/mongodb/lib/operations/db_ops.js:329:54)\nnode_modules/mongodb-core/lib/connection/pool.js:397:18\nprocess._tickCallback (internal/process/next_tick.js:61:11)\n"
    },
    "msg": "can not start server in master mode",
    "time": "2019-09-23T20:29:44.554Z",
    "src": {
        "file": "/usr/src/app/src/index.ts",
        "line": 65,
        "func": "error"
    },
    "v": 0
}
/usr/src/app/node_modules/mongodb-core/lib/error.js:43
return new MongoError(options);
^
MongoError: system collection creation not supported
at Function.create (/usr/src/app/node_modules/mongodb-core/lib/error.js:43:12)
at db.s.topology.insert (/usr/src/app/node_modules/mongodb/lib/operations/db_ops.js:329:54)
at /usr/src/app/node_modules/mongodb-core/lib/connection/pool.js:397:18
at process._tickCallback (internal/process/next_tick.js:61:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @coralproject/talk@5.0.0 start: `NODE_ENV=production node dist/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @coralproject/talk@5.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2019-09-23T20_29_44_619Z-debug.log
```

**Comment by kgardnr** [comment]
Hey @felixdro and @brvaland it's our intention to continue supporting MongoDB and not adding DocumentDB at this time. Thanks though!
