### ISSUE TITLE
dist/manifest.json error

### ISSUE THREAD

**Issue by vadim-berman** [coralproject/talk#2376]
Hello Coral Project team,

We installed a fresh copy of Talk, and upon attempts to get to the /admin/moderate, we get the error:

```
{ Error: ENOENT: no such file or directory, open '/usr/talk/dist/manifest.json'
    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)
    at MANIFESTS.map.f (/usr/talk/middleware/staticTemplate.js:68:10)
    at Array.map (<anonymous>)
    at getManifest (/usr/talk/middleware/staticTemplate.js:67:18)
    at createResolveFactory (/usr/talk/middleware/staticTemplate.js:90:18)
    at module.exports (/usr/talk/middleware/staticTemplate.js:124:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/usr/talk/dist/manifest.json' }
```
What could be the issue? I see there's a `public/manifest.json` but I am wondering whether it's the same. 

#### Do you want to request a **feature** or report a **bug**?

**bug**

#### Version and environment

4.9.1 on Ubuntu 19.04

**Comment by davistrent** [comment]
I had the same issue. I ran `yarn build` again (on a slightly larger machine) and it worked. If the `build` script is hanging or not completing correctly, your server may be undersized.

**Comment by vadim-berman** [comment]
Thanks, it worked.
