### ISSUE TITLE
Talk v5 doesn't start

### ISSUE THREAD

**Issue by mzch** [coralproject/talk#2566]
**Expected behavior:**
talk v5 will start by using `npm run start`

**Actual behavior:**
talk v5 does not start

- console log
```
Sep 13 01:12:58 n23 npm[20634]: > @coralproject/talk@5.0.0 start /srv/talk/talk
Sep 13 01:12:58 n23 npm[20634]: > NODE_ENV=production node dist/index.js
Sep 13 01:13:22 n23 npm[20634]: {"name":"coral","clusterNode":"master","hostname":"n23","pid":20648,"level":30,"msg":"mongodb autoindexing is enabled, starting indexing","time":"2019-09-13T08:13:22.601Z","src":{"file":"/srv/talk/talk/src/core/server/index.ts","line":187,"func":"info"},"v":0}
Sep 13 01:13:27 n23 npm[20634]: {"name":"coral","clusterNode":"worker.2","hostname":"n23","pid":20674,"level":30,"queries":106,"msg":"loaded persisted queries","time":"2019-09-13T08:13:27.330Z","src":{"file":"/srv/talk/talk/src/core/server/graph/tenant/persisted/loader.ts","line":65,"func":"info"},"v":0}
Sep 13 01:13:27 n23 npm[20634]: {"name":"coral","clusterNode":"worker.1","hostname":"n23","pid":20667,"level":30,"queries":106,"msg":"loaded persisted queries","time":"2019-09-13T08:13:27.332Z","src":{"file":"/srv/talk/talk/src/core/server/graph/tenant/persisted/loader.ts","line":65,"func":"info"},"v":0}
Sep 13 01:13:27 n23 npm[20634]: {"name":"coral","clusterNode":"worker.2","hostname":"n23","pid":20674,"level":30,"port":3000,"msg":"now listening","time":"2019-09-13T08:13:27.584Z","src":{"file":"/srv/talk/talk/src/core/server/index.ts","line":331,"func":"info"},"v":0}
Sep 13 01:13:27 n23 npm[20634]: {"name":"coral","clusterNode":"worker.1","hostname":"n23","pid":20667,"level":30,"port":3000,"msg":"now listening","time":"2019-09-13T08:13:27.600Z","src":{"file":"/srv/talk/talk/src/core/server/index.ts","line":331,"func":"info"},"v":0}
Sep 13 01:13:28 n23 npm[20634]: {"name":"coral","clusterNode":"master","hostname":"n23","pid":20648,"collectionName":"queries","level":50,"err":{"message":"E11000 duplicate key error collection: coral.queries index: id_1 dup key: { id: \"123b604c9409b189ecc4f4549b5388e9\" }","name":"MongoError","stack":"Connection.<anonymous> (node_modules/mongodb-core/lib/connection/pool.js:443:61)\nConnection.emit (events.js:198:13)\nprocessMessage (node_modules/mongodb-core/lib/connection/connection.js:364:10)\nSocket.<anonymous> (node_modules/mongodb-core/lib/connection/connection.js:533:15)\nSocket.emit (events.js:198:13)\naddChunk (_stream_readable.js:288:12)\nreadableAddChunk (_stream_readable.js:269:11)\nSocket.Readable.push (_stream_readable.js:224:10)\nTCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)\n"},"indexSpec":{"id":1},"indexOptions":{"unique":true},"msg":"could not create index","time":"2019-09-13T08:13:28.820Z","src":{"file":"/srv/talk/talk/src/core/server/models/helpers/indexing.ts","line":39,"func":"error"},"v":0}
Sep 13 01:13:28 n23 npm[20634]: {"name":"coral","clusterNode":"master","hostname":"n23","pid":20648,"level":50,"err":{"message":"E11000 duplicate key error collection: coral.queries index: id_1 dup key: { id: \"123b604c9409b189ecc4f4549b5388e9\" }","name":"MongoError","stack":"Connection.<anonymous> (node_modules/mongodb-core/lib/connection/pool.js:443:61)\nConnection.emit (events.js:198:13)\nprocessMessage (node_modules/mongodb-core/lib/connection/connection.js:364:10)\nSocket.<anonymous> (node_modules/mongodb-core/lib/connection/connection.js:533:15)\nSocket.emit (events.js:198:13)\naddChunk (_stream_readable.js:288:12)\nreadableAddChunk (_stream_readable.js:269:11)\nSocket.Readable.push (_stream_readable.js:224:10)\nTCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)\n"},"msg":"can not start server in master mode","time":"2019-09-13T08:13:28.833Z","src":{"file":"/srv/talk/talk/src/index.ts","line":65,"func":"error"},"v":0}
Sep 13 01:13:28 n23 npm[20634]: /srv/talk/talk/node_modules/mongodb-core/lib/connection/pool.js:443
Sep 13 01:13:28 n23 npm[20634]:           return handleOperationCallback(self, workItem.cb, new MongoError(responseDoc));
Sep 13 01:13:28 n23 npm[20634]:                                                             ^
Sep 13 01:13:28 n23 npm[20634]: MongoError: E11000 duplicate key error collection: coral.queries index: id_1 dup key: { id: "123b604c9409b189ecc4f4549b5388e9" }
Sep 13 01:13:28 n23 npm[20634]:     at Connection.<anonymous> (/srv/talk/talk/node_modules/mongodb-core/lib/connection/pool.js:443:61)
Sep 13 01:13:28 n23 npm[20634]:     at Connection.emit (events.js:198:13)
Sep 13 01:13:28 n23 npm[20634]:     at processMessage (/srv/talk/talk/node_modules/mongodb-core/lib/connection/connection.js:364:10)
Sep 13 01:13:28 n23 npm[20634]:     at Socket.<anonymous> (/srv/talk/talk/node_modules/mongodb-core/lib/connection/connection.js:533:15)
Sep 13 01:13:28 n23 npm[20634]:     at Socket.emit (events.js:198:13)
Sep 13 01:13:28 n23 npm[20634]:     at addChunk (_stream_readable.js:288:12)
Sep 13 01:13:28 n23 npm[20634]:     at readableAddChunk (_stream_readable.js:269:11)
Sep 13 01:13:28 n23 npm[20634]:     at Socket.Readable.push (_stream_readable.js:224:10)
Sep 13 01:13:28 n23 npm[20634]:     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
Sep 13 01:13:28 n23 npm[20634]: npm ERR! code ELIFECYCLE
Sep 13 01:13:28 n23 npm[20634]: npm ERR! errno 1
Sep 13 01:13:28 n23 npm[20634]: npm ERR! @coralproject/talk@5.0.0 start: `NODE_ENV=production node dist/index.js`
Sep 13 01:13:28 n23 npm[20634]: npm ERR! Exit status 1
Sep 13 01:13:28 n23 npm[20634]: npm ERR!
Sep 13 01:13:28 n23 npm[20634]: npm ERR! Failed at the @coralproject/talk@5.0.0 start script.
Sep 13 01:13:28 n23 npm[20634]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Sep 13 01:13:28 n23 npm[20634]: npm ERR! A complete log of this run can be found in:
Sep 13 01:13:28 n23 npm[20634]: npm ERR!     /srv/talk/.npm/_logs/2019-09-13T08_13_28_878Z-debug.log
```
- npm log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @coralproject/talk@5.0.0~prestart: @coralproject/talk@5.0.0
6 info lifecycle @coralproject/talk@5.0.0~start: @coralproject/talk@5.0.0
7 verbose lifecycle @coralproject/talk@5.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle @coralproject/talk@5.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/srv/talk/talk/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle @coralproject/talk@5.0.0~start: CWD: /srv/talk/talk
10 silly lifecycle @coralproject/talk@5.0.0~start: Args: [ '-c', 'NODE_ENV=production node dist/index.js' ]
11 silly lifecycle @coralproject/talk@5.0.0~start: Returned: code: 1  signal: null
12 info lifecycle @coralproject/talk@5.0.0~start: Failed to exec start script
13 verbose stack Error: @coralproject/talk@5.0.0 start: `NODE_ENV=production node dist/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid @coralproject/talk@5.0.0
15 verbose cwd /srv/talk/talk
16 verbose Linux 4.19.0-6-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
18 verbose node v10.16.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error @coralproject/talk@5.0.0 start: `NODE_ENV=production node dist/index.js`
22 error Exit status 1
23 error Failed at the @coralproject/talk@5.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
**Related Issues:** 

**Versions:**

- NodeJS: v10.16.3
- NPM: 6.9.0
- MongoDB: 4.2.0
- Redis: 5.0.3
- Browser:
- OS: Debian GNU/Linux 10 (Buster)

**Comment by mzch** [comment]
Thanks, @wyattjoh. Fixed this issue.
