### ISSUE TITLE
Redis error, tenant lost

### ISSUE THREAD

**Issue by kenara** [coralproject/talk#3573]
Several times now, after running successfully for a number of hours in development mode (console), Coral stops. I have been able to add stories and comments, stop and start Coral in development and production modes, reboot the server and restart Coral but when this error hits, what I understand to be my "tenant" - auth and email config, users, stories, etc - all are lost. After restarting Coral, I am prompted to start over with the Installation.

The following errors seem to be related to Redis but I don't understand how that relates to the loss of my tenant.

Here's a sample of a long repetitive series:

> BRPOPLPUSH ReplyError: READONLY You can't write against a read only slave.
>     at parseError (/talk-6.10.0/node_modules/redis-parser/lib/parser.js:179:12)
>     at parseType (/talk-6.10.0/node_modules/redis-parser/lib/parser.js:302:14) {
>   command: {
>     name: 'brpoplpush',
>     args: [ '{queue}:scraper:wait', '{queue}:scraper:active', '5' ]
>   }
> }
> BRPOPLPUSH ReplyError: READONLY You can't write against a read only slave.
>     at parseError (/talk-6.10.0/node_modules/redis-parser/lib/parser.js:179:12)
>     at parseType (/talk-6.10.0/node_modules/redis-parser/lib/parser.js:302:14) {
>   command: {
>     name: 'brpoplpush',
>     args: [
>       '{queue}:notifications:wait',
>       '{queue}:notifications:active',
>       '5'
>     ]
>   }
> }
> BRPOPLPUSH ReplyError: READONLY You can't write against a read only slave.
>     at parseError (/talk-6.10.0/node_modules/redis-parser/lib/parser.js:179:12)
>     at parseType (/talk-6.10.0/node_modules/redis-parser/lib/parser.js:302:14) {
>   command: {
>     name: 'brpoplpush',
>     args: [ '{queue}:rejector:wait', '{queue}:rejector:active', '5' ]
>   }
> }
> BRPOPLPUSH ReplyError: READONLY You can't write against a read only slave.
>     at parseError (/talk-6.10.0/node_modules/redis-parser/lib/parser.js:179:12)
>     at parseType (/talk-6.10.0/node_modules/redis-parser/lib/parser.js:302:14) {
>   command: {
>     name: 'brpoplpush',
>     args: [ '{queue}:webhook:wait', '{queue}:webhook:active', '5' ]
>   }
> }
> BRPOPLPUSH ReplyError: READONLY You can't write against a read only slave.
>     at parseError (/talk-6.10.0/node_modules/redis-parser/lib/parser.js:179:12)
>     at parseType (/talk-6.10.0/node_modules/redis-parser/lib/parser.js:302:14) {
>   command: {
>     name: 'brpoplpush',
>     args: [ '{queue}:mailer:wait', '{queue}:mailer:active', '5' ]
>   }
> }

Followed by this:

> [2021-06-01T15:30:00.006Z]  INFO: coral/10394 on talk(/talk-6.10.0/src/core/server/cron/scheduled/job.ts:43): now starting scheduled job (jobName="Twice Hourly Account Deletion", jobFrequency="0,30 * * * *", scheduledExecutionID=3a3d8f50-c2ee-11eb-baa4-f33fd844943e)
> [2021-06-01T15:30:00.010Z]  INFO: coral/10394 on talk(/talk-6.10.0/src/core/server/cron/scheduled/job.ts:50): now finished scheduled job (jobName="Twice Hourly Account Deletion", jobFrequency="0,30 * * * *", scheduledExecutionID=3a3d8f50-c2ee-11eb-baa4-f33fd844943e, took=4)
> [2021-06-01T15:35:59.149Z]  INFO: coral/10394 on talk(/talk-6.10.0/src/core/server/graph/plugins/logger.ts:95 in logQuery): graphql query (context=graph, contextID=104ce820-c2ef-11eb-baa4-f33fd844943e, tenantID=fa3cc888-bf1b-403b-b3a7-5f7e68b03417, responseTime=1, authenticated=false, userID=null, persistedQueryID=8769cb60b7aed7b2ae3aa756c87e5086, persistedQueryBundle=admin, persistedQueryVersion=6.10.0, operation=query, operationName=AuthCheckRouteQuery)
> [2021-06-01T15:35:59.159Z]  INFO: coral/10394 on talk(/talk-6.10.0/src/core/server/graph/plugins/logger.ts:95 in logQuery): graphql query (context=graph, contextID=104ee3f0-c2ef-11eb-baa4-f33fd844943e, tenantID=fa3cc888-bf1b-403b-b3a7-5f7e68b03417, responseTime=0, authenticated=false, userID=null, persistedQueryID=23ee4236deee6ca94961e2ceb83296fa, persistedQueryBundle=admin, persistedQueryVersion=6.10.0, operation=query, operationName=MainRouteQuery)
> [2021-06-01T15:35:59.244Z]  INFO: coral/10394 on talk(/talk-6.10.0/src/core/server/graph/plugins/logger.ts:95 in logQuery): graphql query (context=graph, contextID=104f5920-c2ef-11eb-baa4-f33fd844943e, tenantID=fa3cc888-bf1b-403b-b3a7-5f7e68b03417, responseTime=82, authenticated=false, userID=null, persistedQueryID=f22aacccb0d47bdc5469c90ce3baa984, persistedQueryBundle=admin, persistedQueryVersion=6.10.0, operation=query, operationName=StoriesRouteQuery)
> [2021-06-01T15:35:59.250Z] ERROR: coral/10394 on talk(/talk-6.10.0/src/core/server/graph/plugins/logger.ts:25 in logAndReportError): graphql query error (context=graph, contextID=104f5920-c2ef-11eb-baa4-f33fd844943e, tenantID=fa3cc888-bf1b-403b-b3a7-5f7e68b03417, report=null)
>     err: {
>       "message": "USER_NOT_ENTITLED",
>       "name": "UserForbiddenError",
>       "stack": "auth (src/core/server/graph/directives/auth.ts:185:9)\nnewFieldConfig.resolve (dist/schema/src/attachDirectiveResolvers.js:20:32)\nfield.resolve (node_modules/graphql-extensions/src/index.ts:274:18)\nfield.resolve (node_modules/apollo-server-core/src/utils/schemaInstrumentation.ts:103:18)\nresolveFieldValueOrError (node_modules/graphql/execution/execute.js:467:18)\nresolveField (node_modules/graphql/execution/execute.js:434:16)\nexecuteFields (node_modules/graphql/execution/execute.js:275:18)\ncollectAndExecuteSubfields (node_modules/graphql/execution/execute.js:713:10)\ncompleteObjectValue (node_modules/graphql/execution/execute.js:703:10)\ncompleteValue (node_modules/graphql/execution/execute.js:591:12)\ncompleteValue (node_modules/graphql/execution/execute.js:557:21)\ncompleteValueCatchingError (node_modules/graphql/execution/execute.js:495:19)\nresolveField (node_modules/graphql/execution/execute.js:435:10)\nexecuteFields (node_modules/graphql/execution/execute.js:275:18)\nexecuteOperation (node_modules/graphql/execution/execute.js:219:122)\nexecuteImpl (node_modules/graphql/execution/execute.js:104:14)\n",
>       "id": "1050dfc0-c2ef-11eb-baa4-f33fd844943e",
>       "context": {
>         "pub": {},
>         "pvt": {
>           "reason": "user does not have permission to access the resource",
>           "resource": "settings.multisite",
>           "operation": "query",
>           "unscoped": false
>         }
>       }
>     }
> [2021-06-01T15:35:59.397Z]  INFO: coral/10394 on talk(/talk-6.10.0/src/core/server/graph/plugins/logger.ts:95 in logQuery): graphql query (context=graph, contextID=1071fc50-c2ef-11eb-baa4-f33fd844943e, tenantID=fa3cc888-bf1b-403b-b3a7-5f7e68b03417, responseTime=2, authenticated=false, userID=null, persistedQueryID=b4130c76a429d58fd74df3b4c5043e30, persistedQueryBundle=admin, persistedQueryVersion=6.10.0, operation=query, operationName=LoginRouteQuery)
> [2021-06-01T15:36:10.818Z] ERROR: coral/10394 on talk(/talk-6.10.0/src/core/server/app/middleware/error.ts:78 in wrapAndReport): http error (context=http, contextID=174014e0-c2ef-11eb-baa4-f33fd844943e, tenantID=fa3cc888-bf1b-403b-b3a7-5f7e68b03417, url=/api/auth/local, method=POST, statusCode=401, host=talk.mysite.org, ip=::ffff:123.45.67.89)
>     userAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0
>     --
>     err: {
>       "message": "INVALID_CREDENTIALS",
>       "name": "InvalidCredentialsError",
>       "stack": "Strategy._verify (src/core/server/app/middleware/passport/strategies/local.ts:46:19)\nrunMicrotasks (<anonymous>)\n",
>       "id": "17425ed0-c2ef-11eb-baa4-f33fd844943e",
>       "context": {
>         "pub": {},
>         "pvt": {
>           "reason": "user not found"
>         }
>       }
>     }
> [2021-06-01T15:36:39.733Z] ERROR: coral/10394 on talk(/talk-6.10.0/src/core/server/app/middleware/error.ts:78 in wrapAndReport): http error (context=http, contextID=287e24e0-c2ef-11eb-baa4-f33fd844943e, tenantID=fa3cc888-bf1b-403b-b3a7-5f7e68b03417, url=/api/auth/local, method=POST, statusCode=401, host=talk.mysite.org, ip=::ffff:123.45.67.89)
>     userAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0
>     --
>     err: {
>       "message": "INVALID_CREDENTIALS",
>       "name": "InvalidCredentialsError",
>       "stack": "Strategy._verify (src/core/server/app/middleware/passport/strategies/local.ts:46:19)\nrunMicrotasks (<anonymous>)\n",
>       "id": "287f0f40-c2ef-11eb-baa4-f33fd844943e",
>       "context": {
>         "pub": {},
>         "pvt": {
>           "reason": "user not found"
>         }
>       }
>     }
> [2021-06-01T15:36:49.135Z]  INFO: coral/10394 on talk(/talk-6.10.0/src/core/server/graph/plugins/logger.ts:95 in logQuery): graphql query (context=graph, contextID=2e180330-c2ef-11eb-baa4-f33fd844943e, tenantID=fa3cc888-bf1b-403b-b3a7-5f7e68b03417, responseTime=6, authenticated=false, userID=null, persistedQueryID=b4130c76a429d58fd74df3b4c5043e30, persistedQueryBundle=admin, persistedQueryVersion=6.10.0, operation=query, operationName=LoginRouteQuery)
> 

Restarting, I get this line among the otherwise normal startup messages:

`[2021-06-01T15:37:44.967Z]  INFO: coral/14455 on talk(/talk-6.10.0/src/core/server/index.ts:290 in process): no tenants are installed, skipping running migrations`

**Comment by kenara** [comment]
This issue would probably be better for Stackoverflow. Come to think of it, let's try and see some Coral activity on SO...

I find it paradoxical that, despite some great documentation on best practices for online communities put out by this project, there does not appear to be a "Coral Community." Could be a cool opportunity for dogfooding the product.. 🤓

Closing.
