### ISSUE TITLE
Can't compile 7.2.2: Error: defaultLocale: must be one of the possible values ...

### ISSUE THREAD

**Issue by jacotec** [coralproject/talk#4034]
**Expected behavior:**

I should be able to compile the project following the docs

**Actual behavior:**

I'm getting an error in the step "npm run build":

```
> @coralproject/talk@7.2.2 build:server
> gulp server

[14:40:40] Using gulpfile /opt/talk/gulpfile.js
[14:40:40] Starting 'server'...
[14:40:40] Starting 'server:schema'...
[14:40:41] Finished 'server:schema' after 884 ms
[14:40:41] Starting 'server:scripts'...
[14:40:41] Starting 'server:static'...
[14:40:41] Starting 'locales'...

/opt/talk/node_modules/convict/lib/convict.js:686
          throw new Error(output);
                ^
Error: defaultLocale: must be one of the possible values: ["af-ZA","ar-AE","en-US","pt-BR","es","de","tr-TR","hu","id-ID","it-IT","ja-JP","de-CH","nl-NL","da","fr-FR","ro","fi-FI","sv","pl","ru","nb-NO","zh-CN"]: value was "de_DE"
    at Object.validate (/opt/talk/node_modules/convict/lib/convict.js:686:17)
    at Object.<anonymous> (/opt/talk/scripts/build.ts:27:8)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.m._compile (/opt/talk/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (/opt/talk/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at main (/opt/talk/node_modules/ts-node/src/bin.ts:198:14)
    at Object.<anonymous> (/opt/talk/node_modules/ts-node/src/bin.ts:288:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
ERROR: "build:client" exited with 1.
```

**Related Issues:** 

**Versions:**

- NodeJS: 14.18.0
- NPM: 8.0
- MongoDB: 4.4
- Redis: 5.something
- Browser:
- OS: Ubuntu 20.04 LTS

**Comment by jacotec** [comment]
Found it ... wrong locale defined in .env:

Must be "LOCALE=de" instead of "LOCALE=de_DE"
