### ISSUE TITLE
npm run generate:css-types - Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by voitto** [coralproject/talk#4306]
I'm trying to install Coral on Ubuntu 20.04 with Node 14.18.3 and npm 6.14.15, when I try to "npm run build" I get an error.

the output of the log looks like the following, would be most appreciative if anyone can share a possible workaround, thank you!

-Brian

```
npm run generate:css-types

> @coralproject/talk@8.4.2 generate:css-types /home/atoms/talk
> tcm src/core/client/

/usr/lib/node_modules/tcm/node_modules/promisify-node/index.js:86
    if (Object.keys(exports.prototype).length) {
               ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at processExports (/usr/lib/node_modules/tcm/node_modules/promisify-node/index.js:86:16)
    at /usr/lib/node_modules/tcm/node_modules/promisify-node/index.js:137:23
    at Array.forEach (<anonymous>)
    at processExports (/usr/lib/node_modules/tcm/node_modules/promisify-node/index.js:132:6)
    at /usr/lib/node_modules/tcm/node_modules/promisify-node/index.js:121:7
    at Array.filter (<anonymous>)
    at processExports (/usr/lib/node_modules/tcm/node_modules/promisify-node/index.js:115:6)
    at module.exports (/usr/lib/node_modules/tcm/node_modules/promisify-node/index.js:164:10)
    at Object.<anonymous> (/usr/lib/node_modules/tcm/lib/utils/index.js:38:53)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @coralproject/talk@8.4.2 generate:css-types: `tcm src/core/client/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @coralproject/talk@8.4.2 generate:css-types script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
```

```

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'generate:css-types'
1 verbose cli ]
2 info using npm@6.14.15
3 info using node@v14.18.3
4 verbose run-script [
4 verbose run-script   'pregenerate:css-types',
4 verbose run-script   'generate:css-types',
4 verbose run-script   'postgenerate:css-types'
4 verbose run-script ]
5 info lifecycle @coralproject/talk@8.4.2~pregenerate:css-types: @coralproject/talk@8.4.2
6 info lifecycle @coralproject/talk@8.4.2~generate:css-types: @coralproject/talk@8.4.2
7 verbose lifecycle @coralproject/talk@8.4.2~generate:css-types: unsafe-perm in lifecycle true
8 verbose lifecycle @coralproject/talk@8.4.2~generate:css-types: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/atoms/talk/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/atoms/talk/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/atoms/talk/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle @coralproject/talk@8.4.2~generate:css-types: CWD: /home/atoms/talk
10 silly lifecycle @coralproject/talk@8.4.2~generate:css-types: Args: [ '-c', 'tcm src/core/client/' ]
11 silly lifecycle @coralproject/talk@8.4.2~generate:css-types: Returned: code: 1  signal: null
12 info lifecycle @coralproject/talk@8.4.2~generate:css-types: Failed to exec generate:css-types script
13 verbose stack Error: @coralproject/talk@8.4.2 generate:css-types: `tcm src/core/client/`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1058:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
14 verbose pkgid @coralproject/talk@8.4.2
15 verbose cwd /home/atoms/talk
16 verbose Linux 5.4.0-147-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "run" "generate:css-types"
18 verbose node v14.18.3
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error @coralproject/talk@8.4.2 generate:css-types: `tcm src/core/client/`
22 error Exit status 1
23 error Failed at the @coralproject/talk@8.4.2 generate:css-types script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by tessalt** [comment]
hi there, try using npm version 8.0.0
