### ISSUE TITLE
Local / Remote plugin require is not consistent

### ISSUE THREAD

**Issue by marcosnils** [coralproject/talk#471]
### Expected behavior
Consistency while using `require` to use a Talk dependency in the plugin

### Actual behavior
`require` works differently depending if the plugin is local or remote.

### Steps to reproduce behavior
If you use the following plugin (https://github.com/mantika/sherloq-talk/blob/master/index.js) locally by copying the index.js in the proper folder, `require` works as expected. However, if you setup the plugin to be configured remotely through NPM (https://www.npmjs.com/package/sherloq-talk),  you get an error as `require` can't resolve imports.

```
talk_1   | Error: plugin 'sherloq-talk' could not be required from '/usr/src/app/node_modules/sherloq-ta
lk/index.js': Cannot find module 'services/comments.js'                                                 
talk_1   |     at PluginSection.plugins.itteratePlugins.map (/usr/src/app/plugins.js:104:23)            
talk_1   |     at Array.map (native)                                                                    
talk_1   |     at new PluginSection (/usr/src/app/plugins.js:91:45)                                     
talk_1   |     at new PluginManager (/usr/src/app/plugins.js:142:32)                                    
talk_1   |     at Object.<anonymous> (/usr/src/app/services/plugins.js:3:18)                            
talk_1   |     at Module._compile (module.js:571:32)                                                    
talk_1   |     at Object.Module._extensions..js (module.js:580:10)                                      
talk_1   |     at Module.load (module.js:488:32)                                                        
talk_1   |     at tryModuleLoad (module.js:447:12)                                                      
talk_1   |     at Function.Module._load (module.js:439:3)                                               
talk_1   |     at Module.require (module.js:498:17)                                                     
talk_1   |     at require (internal/module.js:20:19)                                                    
talk_1   |     at Object.<anonymous> (/usr/src/app/app.js:7:17)                                         
talk_1   |     at Module._compile (module.js:571:32)                                                    
talk_1   |     at Object.Module._extensions..js (module.js:580:10)                                      
talk_1   |     at Module.load (module.js:488:32)                                                        
talk_1   | /usr/src/app/plugins.js:105                                                                  
talk_1   |         throw e;                                                                             
talk_1   |         ^                                                                                    
talk_1   |                                                                                              

```

**Comment by wyattjoh** [comment]
I'll take a look at this today @marcosnils!
