### ISSUE TITLE
EBADCSRFTOKEN on install page

### ISSUE THREAD

**Issue by petitpress1** [coralproject/talk#541]
I have just install docker version and have problems setting it up. I'm getting bad csrftoken exception while specifying domain list in last step on:

http://localhost:5000/admin/install

Can you please help me find out what am I missing?

```
talk_1   |     { ForbiddenError: invalid csrf token
talk_1   |     at csrf (/usr/src/app/node_modules/csurf/index.js:112:19)
talk_1   |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
talk_1   |     at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
talk_1   |     at /usr/src/app/node_modules/express/lib/router/index.js:284:7
talk_1   |     at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
talk_1   |     at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
talk_1   |     at SessionStrategy.strategy.pass (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:325:9)
talk_1   |     at SessionStrategy.authenticate (/usr/src/app/node_modules/passport/lib/strategies/session.js:71:10)
talk_1   |     at attempt (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:348:16)
talk_1   |     at authenticate (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:349:7)
talk_1   |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
talk_1   |     at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
talk_1   |     at /usr/src/app/node_modules/express/lib/router/index.js:284:7
talk_1   |     at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
talk_1   |     at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
talk_1   |     at initialize (/usr/src/app/node_modules/passport/lib/middleware/initialize.js:53:5)
talk_1   |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
talk_1   |     at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
talk_1   |     at /usr/src/app/node_modules/express/lib/router/index.js:284:7
talk_1   |     at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
talk_1   |     at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
talk_1   |     at session (/usr/src/app/node_modules/express-session/index.js:454:7) code: 'EBADCSRFTOKEN' }
```

**Comment by wyattjoh** [comment]
What you're likely running into @petitpress is when you run the application in production mode, the application requires that you serve the application with HTTPS. You can use a tool like ngrok or a web server like Caddy to provide an SSL certificate for testing.
