### ISSUE TITLE
Redis3 cluster mode enabled

### ISSUE THREAD

**Issue by thiagonache** [coralproject/talk#901]
### Expected behavior
Works normally.

### Actual behavior
Crashes when redis3 answer MOVED to the application. 
More details about [MOVED](https://redis.io/topics/cluster-spec) 

### Steps to reproduce behavior
Deploy application and set backend using redis3 with cluster mode enabled.

If that's expected, can you guys add it on documentation, please?

Best regards,

Thiago

**Comment by wyattjoh** [comment]
Hi @thiagonache! Can you set `DEBUG=talk:services:redis` and run the application and try to reproduce the error and post the logs? Just so I know how it's failing for you.

**Comment by wyattjoh** [comment]
I've poked the maintainer of our graphql pubsub client, `graphql-redis-subscriptions` about our desire to get cluster support via ioredis, which will be supported when they merge [this PR](https://github.com/davidyaha/graphql-redis-subscriptions/pull/78).

Until then we're still tied to using `node_redis` which doesn't support clustering yet.

**Comment by thiagonache** [comment]
okay. I'm assuming you don't need the test anymore, is that correct?

**Comment by thiagonache** [comment]
what do you think about adding a note in the documentation about it?

**Comment by wyattjoh** [comment]
I've pushed ioredis support to a branch that you can test!

https://github.com/coralproject/talk/tree/ioredis

Let me know if that works for you.

**Comment by thiagonache** [comment]
awesome. going to test in a few. thx for that.

**Comment by eduardotrova** [comment]
Hi @wyattjoh 

I am a member of development team thats working with @thiagonache on our coral project talk.

We've been testing new version and apparently it's not honoring environment variables. Please, find application error and container inspect.

yarn start v0.27.5
$ ./bin/cli serve -j -w
Error connecting to redis: { Error: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379 }
events.js:182
      throw er; // Unhandled 'error' event
      ^
Error: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)
error Command failed with exit code 1.

    Environment:
      TALK_MONGO_URL:           mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/talk?replicaSet=rs0
      TALK_REDIS_URL:           redis://redis
      TALK_ROOT_URL:            http://nononono/
      TALK_JWT_SECRET:          XXXX
      TALK_SESSION_SECRET:      XXXX
      TALK_SMTP_HOST:           XXXXX
      TALK_SMTP_PORT:           XXXX
      TALK_FACEBOOK_APP_ID:     XXXXXX
      TALK_FACEBOOK_APP_SECRET: XXXXXXXX
      TALK_RECAPTCHA_SECRET:    XXXXX
      TALK_RECAPTCHA_PUBLIC:    XXXXXXX
      TALK_ESTADAO_AUTH_URL:    XXXXXXXXXX

**Comment by wyattjoh** [comment]
Can you post the output when you set `DEBUG=talk:services:redis` @eduardotrova? What commit are you at?

**Comment by eduardotrova** [comment]
the output is:

yarn start v0.27.5
$ ./bin/cli serve -j -w
Error connecting to redis: { Error: connect ECONNREFUSED 127.0.0.1:6379
at Object._errnoException (util.js:1041:11)
at _exceptionWithHostPort (util.js:1064:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)
code: 'ECONNREFUSED',
errno: 'ECONNREFUSED',
syscall: 'connect',
address: '127.0.0.1',
port: 6379 }
events.js:182
throw er; // Unhandled 'error' event
^
Error: connect ECONNREFUSED 127.0.0.1:6379
at Object._errnoException (util.js:1041:11)
at _exceptionWithHostPort (util.js:1064:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)
error Command failed with exit code 1.

I use this: https://github.com/coralproject/talk/tree/ioredis

**Comment by wyattjoh** [comment]
The output doesn't contain any debug logs from redis, what commit are you using?

**Comment by thiagonache** [comment]
my guess is that env var is not being honored, so there's no debug output

**Comment by wyattjoh** [comment]
If you are using docker compose, you will have to set `Environment` to `environment`, that may be the issue.

**Comment by thiagonache** [comment]
no. this is the docker inspect output. that's why we have E and not e

**Comment by wyattjoh** [comment]
What image are you using? What tag?

Can you post the output of:

```
docker images | grep coralproject/talk
```

**Comment by thiagonache** [comment]
we built our own image with your branch. I'm not sure what's the idea of getting the image id.

**Comment by eduardotrova** [comment]
If helps inside the package.json we see:
"name": "talk",
  "version": "3.4.0",

**Comment by wyattjoh** [comment]
The issue is that I can't reproduce the problem on my side, so I'm not sure where the problems are coming up. Our configuration uses `process.env` to retrieve the variables, there isn't another way for the environment to be overridden. Have you modified the `CMD` on the Dockerfile?

**Comment by thiagonache** [comment]
Execution with debug:
```
yarn start v0.27.5
$ ./bin/cli serve -j -w
2017-08-31T23:53:55.233Z talk:services:redis client created
2017-08-31T23:53:55.234Z talk:services:redis client created
2017-08-31T23:53:55.236Z talk:services:redis client created
2017-08-31T23:53:55.236Z talk:services:redis client created
2017-08-31T23:53:55.237Z talk:services:redis client created
Error connecting to redis: { Error: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379 }
events.js:182
      throw er; // Unhandled 'error' event
      ^
Error: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)
error Command failed with exit code 1.
```

Variables were present:
```
PATH=/usr/src/app/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=talk-k1n7k
TALK_FACEBOOK_APP_SECRET=bla
TALK_MONGO_URL=mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/talk?replicaSet=rs0
TALK_REDIS_URL=redis://redis
DEBUG=talk:services:redis
TALK_ROOT_URL=http://35.188.250.255/
TALK_JWT_SECRET=bla
TALK_FACEBOOK_APP_ID=bla
REDIS_4_PORT_6379_TCP_PORT=6379
```
The debug messages aren't helpful. Is there another level or something like that?

**Comment by thiagonache** [comment]
Is there a process to generate a new docker or I just need to build the dockerfile as usual?

**Comment by thiagonache** [comment]
there's a public image on dockerhub at thiagonache/talk:redisio

**Comment by wyattjoh** [comment]
We discovered the issue @thiagonache, turns out our `ioredis` package we subbed in didn't mention a breaking change to the configuration api. We thankfully corrected the issue in master now.

**Comment by thiagonache** [comment]
does it mean that I can use redis in cluster mode with the new master
branch?

**Comment by wyattjoh** [comment]
You should be able to, let me know if it still crashes when it gets the "MOVED" answer.

**Comment by thiagonache** [comment]
I'm still facing the same error:
```
yarn start v0.27.5
$ ./bin/cli serve -j -w
2017-09-01T19:10:30.813Z talk:services:redis client created
2017-09-01T19:10:30.814Z talk:services:redis client created
2017-09-01T19:10:30.816Z talk:services:redis client created
2017-09-01T19:10:30.816Z talk:services:redis client created
2017-09-01T19:10:30.817Z talk:services:redis client created
2017-09-01T19:10:30.829Z talk:services:redis client connected
2017-09-01T19:10:30.829Z talk:services:redis client connected
2017-09-01T19:10:30.830Z talk:services:redis client connected
2017-09-01T19:10:30.830Z talk:services:redis client connected
2017-09-01T19:10:30.832Z talk:services:redis client connected
2017-09-01T19:10:30.837Z talk:services:redis client ready
2017-09-01T19:10:30.837Z talk:services:redis client ready
2017-09-01T19:10:30.837Z talk:services:redis client ready
2017-09-01T19:10:30.837Z talk:services:redis client ready
2017-09-01T19:10:30.845Z talk:services:redis client ready
/usr/src/app/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^
ReplyError: MOVED 11958 10.56.2.6:6379
    at JavascriptRedisParser.returnError (/usr/src/app/node_modules/ioredis/lib/redis/parser.js:24:25)
    at JavascriptRedisParser.execute (/usr/src/app/node_modules/redis-parser/lib/parser.js:572:12)
    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/lib/redis/event_handler.js:107:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:585:20)
error Command failed with exit code 1.
```
If you want to see the final image use tag latest of that same image (thiagonache/talk:latest)

Thank you.

**Comment by thiagonache** [comment]
I can give you public endpoints to redis 3 in cluster mode if it would make easier for you.

**Comment by wyattjoh** [comment]
I'll be taking some time next week to review this issue @thiagonache.

**Comment by wyattjoh** [comment]
A PR has been opened @thiagonache, check to see if the documentation and examples work for you.

**Comment by thiagonache** [comment]
@wyattjoh thank you so much. @eduardotrova it's all yours now.

**Comment by eduardotrova** [comment]
ok @thiagonache thanks for all.  @wyattjoh I'll test this in the next days and notice.

**Comment by kgardnr** [comment]
Hey @eduardotrova and @thiagonache, were you able to test this? Does it suit your needs? If so, we will go ahead and merge it :)

**Comment by thiagonache** [comment]
I'm facing another issue now.
$ ./bin/cli serve -j -w
2017-09-26T22:29:29.582Z talk:services:redis client created
2017-09-26T22:29:29.583Z talk:services:redis client created
2017-09-26T22:29:29.585Z talk:services:redis client created
2017-09-26T22:29:29.586Z talk:services:redis client created
2017-09-26T22:29:29.587Z talk:services:redis client created
2017-09-26T22:29:29.628Z talk:services:redis client connected
2017-09-26T22:29:29.628Z talk:services:redis client connected
2017-09-26T22:29:29.628Z talk:services:redis client connected
2017-09-26T22:29:29.628Z talk:services:redis client connected
2017-09-26T22:29:29.632Z talk:services:redis client connected
2017-09-26T22:29:29.639Z talk:services:redis client ready
2017-09-26T22:29:29.662Z talk:services:redis client ready
Pipe tcp://10.59.240.206:80 requires elevated privileges
/usr/src/app/bin/cli-serve:55
  throw error;
  ^
Error: listen EACCES tcp://10.59.240.206:80
    at Object._errnoException (util.js:1026:11)

Did something change?

**Comment by eduardotrova** [comment]
Hello guys

We tested locally (with a localhost env) and it seemed ok, but let's re-test tomorrow in our staging environment with pods on kubernetes.
