### ISSUE TITLE
Stuck on yarn start

### ISSUE THREAD

**Issue by sijomc** [coralproject/talk#995]
Please help me to solve this issue. Where should I configure these variables? Or how can I deploy coral talk without this plugin? 

 yarn start
yarn start v1.0.1
$ ./bin/cli serve -j -w
/root/talk-3.5.1/plugins/talk-plugin-facebook-auth/server/passport.js:32
    throw new Error('Facebook cannot be enabled, missing one of TALK_FACEBOOK_APP_ID, TALK_FACEBOOK_APP_SECRET, TALK_ROOT_URL');
    ^

Error: Facebook cannot be enabled, missing one of TALK_FACEBOOK_APP_ID, TALK_FACEBOOK_APP_SECRET, TALK_ROOT_URL
    at Object.module.exports [as passport] (/root/talk-3.5.1/plugins/talk-plugin-facebook-auth/server/passport.js:32:11)
    at plugins.get.forEach (/root/talk-3.5.1/routes/index.js:76:10)
    at Array.forEach (native)
    at Object.<anonymous> (/root/talk-3.5.1/routes/index.js:71:35)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/talk-3.5.1/app.js:16:16)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/talk-3.5.1/bin/cli-serve:4:13)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
error Command failed with exit code 1.

**Comment by jtnelson** [comment]
1. You'll need to add the TALK_ROOT_URL as an environment variable
e.g.
```
export TALK_ROOT_URL=http://localhost:5000
```

2. You can also add the facebook plugin configuration via environment variables in the same way if you want to use the plugin. If you do not want to use the plugin, you can remove the `talk-plugin`facebook-auth` from https://github.com/coralproject/talk/blob/master/plugins.default.json OR create a copy of that file called `plugins.json` and remove it from there.

**Comment by jtnelson** [comment]
@sijomc i'm going to close this issue for now, but please re-open if the steps above don't work or you have more questions about this.
